# druid生成的公匙
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAK8AmuY729SlnemqGzjaAAPCAr3ksv//JsNftSpsMzXJgjOYSss5WxlQScBr0Kx8c2hHI2ZF+zwRhkAHPdx+SY0CAwEAAQ==
spring:
  datasource:
    username: root
    password: jM3wZkWe8YHVtEycmCRFEPZEnRSFz/EZELoJwsp/YM6qUtuYyGn1PXmpGblHPxBreSFbSdMRI5aeI48jfOWHIQ==
    #?serverTimezone=UTC解决时区的报错 62.234.8.132:3306
    url: jdbc:mysql://127.0.0.1:3306/question?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
      #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
      #则导入 log4j 依赖即可，Maven 地址： https://mvnrepository.com/artifact/log4j/log4j
      filters: stat,wall
      filter:
        config:
          enabled: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: config.decrypt=true;config.decrypt.key=${public-key}


mybatis:
  configuration:
    map-underscore-to-camel-case: true
